//案例数据 type  0 ==>工装，1，私装 
const caseConfig = {
    '0': [
        {
            img: '../static/img/case/sd_2 (2).jpg',
            name: '圣景地产办公室',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/sd_1.jpg',
                '../static/img/case/sd_2 (1).jpg',
                '../static/img/case/sd_2 (2).jpg',
                '../static/img/case/sd_2 (3).jpg',
            ],
            id: '0',
        },
        {
            img: '../static/img/case/tj_1 (1).png',
            name: '田家厨房',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/tj_1 (1).png',
                '../static/img/case/tj_1 (2).png',
                '../static/img/case/tj_1 (3).png',
                '../static/img/case/tj_1 (4).png',
                '../static/img/case/tj_1 (5).png',
            ],
            id: '1',
        }
    ],
    '1':[
        {
            img: '../static/img/case/cjyy (1).jpg',
            name: '春江怡园',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/cjyy (1).jpg',
                '../static/img/case/cjyy (2).jpg',
                '../static/img/case/cjyy (3).jpg',
                '../static/img/case/cjyy (4).jpg',
                '../static/img/case/cjyy (5).jpg',
                '../static/img/case/cjyy (6).jpg',
                '../static/img/case/cjyy (7).jpg',
                '../static/img/case/cjyy (8).jpg',
            ],
            id: '0',
        },
        {
            img: '../static/img/case/dotx (7).jpg',
            name: '东湖天下',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/dotx (1).jpg',
                '../static/img/case/dotx (2).jpg',
                '../static/img/case/dotx (3).jpg',
                '../static/img/case/dotx (4).jpg',
                '../static/img/case/dotx (5).jpg',
                '../static/img/case/dotx (6).jpg',
                '../static/img/case/dotx (7).jpg',
            ],
            id: '1',
        },
        {
            img: '../static/img/case/gyyh (1).jpg',
            name: '公园一号',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/gyyh (1).jpg',
                '../static/img/case/gyyh (2).jpg',
                '../static/img/case/gyyh (3).jpg',
            ],
            id: '2',
        },
        {
            img: '../static/img/case/gchy (1).jpg',
            name: '桂城花园',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/gchy (1).jpg',
                '../static/img/case/gchy (2).jpg',
            ],
            id: '3',
        },
        {
            img: '../static/img/case/hyc (1).jpg',
            name: '花漾城',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/hyc (1).jpg',
                '../static/img/case/hyc (2).jpg',
                '../static/img/case/hyc (3).jpg',
                '../static/img/case/hyc (4).jpg',
            ],
            id: '4',
        },
        {
            img: '../static/img/case/hjxj (1).jpg',
            name: '华锦新城',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/hjxj (1).jpg',
                '../static/img/case/hjxj (2).jpg',
                '../static/img/case/hjxj (3).jpg',
                '../static/img/case/hjxj (4).jpg',
                '../static/img/case/hjxj (5).jpg',
                '../static/img/case/hjxj (6).jpg',
                '../static/img/case/hjxj (7).jpg',
                '../static/img/case/hjxj (8).jpg',
            ],
            id: '5',
        },
        {
            img: '../static/img/case/hr24 (1).jpg',
            name: '华润24',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/hr24 (1).jpg',
                '../static/img/case/hr24 (2).jpg'
            ],
            id: '6',
        },
        {
            img: '../static/img/case/jzc (1).jpg',
            name: '江城著',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/jzc (1).jpg',
                '../static/img/case/jzc (2).jpg',
                '../static/img/case/jzc (3).png',
                '../static/img/case/jzc (4).png',
                '../static/img/case/jzc (5).png',
                '../static/img/case/jzc (6).png',
                '../static/img/case/jzc (7).png',
            ],
            id: '7',
        },{
            img: '../static/img/case/jsw (1).png',
            name: '金沙湾',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/jsw (1).png',
                '../static/img/case/jsw (2).png',
                '../static/img/case/jsw (3).png',
                '../static/img/case/jsw (4).png',
                '../static/img/case/jsw (5).png',
                '../static/img/case/jsw (6).png',
                '../static/img/case/jsw (7).png',
                '../static/img/case/jsw (8).png',
            ],
            id: '8',
        },
        {
            img: '../static/img/case/jxbd (1).jpg',
            name: '锦绣半岛',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/jxbd (1).jpg',
                '../static/img/case/jxbd (2).jpg',
                '../static/img/case/jxbd (3).jpg',
                '../static/img/case/jxbd (4).jpg',
                '../static/img/case/jxbd (5).jpg',
                '../static/img/case/jxbd (6).jpg',
                '../static/img/case/jxbd (7).jpg',
                '../static/img/case/jxbd (8).jpg',
                '../static/img/case/jxbd (9).jpg',
                '../static/img/case/jxbd (10).jpg',
                '../static/img/case/jxbd (11).jpg',
            ],
            id: '9',
        },
        {
            img: '../static/img/case/gxgj (1).jpg',
            name: '凯旋国际',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/gxgj (1).jpg',
                '../static/img/case/gxgj (2).jpg',
                '../static/img/case/gxgj (3).jpg',
                '../static/img/case/gxgj (4).jpg',
                '../static/img/case/gxgj (5).jpg',
                '../static/img/case/gxgj (6).jpg',
            ],
            id: '10',
        },
        {
            img: '../static/img/case/syc (1).jpg',
            name: '山语城',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/syc (1).jpg',
                '../static/img/case/syc (2).jpg',
                '../static/img/case/syc (3).jpg',
                '../static/img/case/syc (4).jpg',
                '../static/img/case/syc (5).png',
                '../static/img/case/syc (6).png',
                '../static/img/case/syc (7).png',
            ],
            id: '11',
        },
        {
            img: '../static/img/case/syczh (1).jpg',
            name: '山语城中户',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/syczh (1).jpg',
                '../static/img/case/syczh (2).jpg',
                '../static/img/case/syczh (3).jpg',
                '../static/img/case/syczh (4).jpg',
                '../static/img/case/syczh (5).jpg',
                '../static/img/case/syczh (6).jpg',
            ],
            id: '12',
        },
        {
            img: '../static/img/case/xjmd (1).jpg',
            name: '香江美地',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/xjmd (1).jpg',
                '../static/img/case/xjmd (2).jpg',
                '../static/img/case/xjmd (3).jpg',
                '../static/img/case/xjmd (4).jpg',
            ],
            id: '13',
        },
        {
            img: '../static/img/case/yjl (1).jpg',
            name: '雅居乐',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/yjl (1).jpg',
                '../static/img/case/yjl (2).jpg',
            ],
            id: '14',
        },
        {
            img: '../static/img/case/yf (1).jpg',
            name: '御峰',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/yf (1).jpg',
                '../static/img/case/yf (2).jpg',
                '../static/img/case/yf (3).jpg',
                '../static/img/case/yf (4).jpg',
                '../static/img/case/yf (5).jpg',
                '../static/img/case/yf (6).jpg',
            ],
            id: '15',
        },
        {
            img: '../static/img/case/ypsy (1).jpg',
            name: '御品尚源',
            time:'2017-04-23 15:49:39',
            imgList:[
                '../static/img/case/ypsy (1).jpg',
                '../static/img/case/ypsy (2).jpg',
                '../static/img/case/ypsy (3).jpg',
                '../static/img/case/ypsy (4).jpg',
                '../static/img/case/ypsy (5).jpg',
                '../static/img/case/ypsy (6).jpg',
                '../static/img/case/ypsy (7).jpg',
                '../static/img/case/ypsy (8).jpg',
                '../static/img/case/ypsy (9).jpg',
                '../static/img/case/ypsy (10).jpg',
                '../static/img/case/ypsy (12).jpg',
                '../static/img/case/ypsy (13).jpg',
                '../static/img/case/ypsy (14).jpg',
                '../static/img/case/ypsy (15).jpg',
                '../static/img/case/ypsy (16).jpg',
            ],
            id: '16',
        }

    ]

}
export default  caseConfig;