const config = [
    {
        txt: '窗帘',
        id: 0,
        imgList:[
            '../static/img/product/cl/chuangliang (1).jpg',
            '../static/img/product/cl/chuangliang (2).jpg',
            '../static/img/product/cl/chuangliang (3).jpg',
            '../static/img/product/cl/chuangliang (4).jpg',
            '../static/img/product/cl/chuangliang (5).jpg',
            '../static/img/product/cl/chuangliang (6).jpg',
            '../static/img/product/cl/chuangliang (7).jpg',
            '../static/img/product/cl/chuangliang (8).jpg',
            '../static/img/product/cl/chuangliang (9).jpg',
            '../static/img/product/cl/chuangliang (10).jpg',
            '../static/img/product/cl/chuangliang (11).jpg',
            '../static/img/product/cl/chuangliang (12).jpg',
            '../static/img/product/cl/chuangliang (13).jpg',
            '../static/img/product/cl/chuangliang (14).jpg',
            '../static/img/product/cl/chuangliang (15).jpg',
            '../static/img/product/cl/chuangliang (16).jpg',
            '../static/img/product/cl/chuangliang (17).jpg',
            '../static/img/product/cl/chuangliang (18).jpg',
            '../static/img/product/cl/chuangliang (19).jpg',
            '../static/img/product/cl/chuangliang (20).jpg',
            '../static/img/product/cl/chuangliang (21).jpg',
            '../static/img/product/cl/chuangliang (22).jpg',
            '../static/img/product/cl/chuangliang (23).jpg',
            '../static/img/product/cl/chuangliang (24).jpg',
            '../static/img/product/cl/chuangliang (25).jpg',
            '../static/img/product/cl/chuangliang (26).jpg',
            '../static/img/product/cl/chuangliang (27).jpg',
            '../static/img/product/cl/chuangliang (28).jpg',
            '../static/img/product/cl/chuangliang (29).jpg',
            '../static/img/product/cl/chuangliang (30).jpg',
        ],
    },
    {
        txt: '灯具',
        id: 1,
        imgList:[
            '../static/img/product/dj/dj (1).jpg',
            '../static/img/product/dj/dj (2).jpg',
            '../static/img/product/dj/dj (3).jpg',
            '../static/img/product/dj/dj (4).jpg',
            '../static/img/product/dj/dj (5).jpg',
            '../static/img/product/dj/dj (6).jpg',
            '../static/img/product/dj/dj (7).jpg',
            '../static/img/product/dj/dj (8).jpg',
            '../static/img/product/dj/dj (9).jpg',
            '../static/img/product/dj/dj (10).jpg',
            '../static/img/product/dj/dj (11).jpg',
            '../static/img/product/dj/dj (12).jpg',
            '../static/img/product/dj/dj (13).jpg',
            '../static/img/product/dj/dj (14).jpg',
            '../static/img/product/dj/dj (15).jpg',
            '../static/img/product/dj/dj (16).jpg',
            '../static/img/product/dj/dj (17).jpg',
            '../static/img/product/dj/dj (18).jpg',
            '../static/img/product/dj/dj (19).jpg',
            '../static/img/product/dj/dj (20).jpg',
            '../static/img/product/dj/dj (21).jpg',
            '../static/img/product/dj/dj (22).jpg',
            '../static/img/product/dj/dj (23).jpg',
        ],
    },
    {
        txt: '地毯',
        id: 2,
        imgList:[
            '../static/img/product/dt/dt (1).jpg',
            '../static/img/product/dt/dt (2).jpg',
            '../static/img/product/dt/dt (3).jpg',
            '../static/img/product/dt/dt (4).jpg',
            '../static/img/product/dt/dt (5).jpg',
            '../static/img/product/dt/dt (6).jpg',
            '../static/img/product/dt/dt (7).jpg',
            '../static/img/product/dt/dt (8).jpg',
            '../static/img/product/dt/dt (9).jpg',
            '../static/img/product/dt/dt (10).jpg',
            '../static/img/product/dt/dt (11).jpg',
            '../static/img/product/dt/dt (12).jpg',
            '../static/img/product/dt/dt (13).jpg',
            '../static/img/product/dt/dt (14).jpg',
            '../static/img/product/dt/dt (15).jpg',
            '../static/img/product/dt/dt (16).jpg',
            '../static/img/product/dt/dt (17).jpg',
            '../static/img/product/dt/dt (18).jpg',
            '../static/img/product/dt/dt (19).jpg',
            '../static/img/product/dt/dt (20).jpg',
            '../static/img/product/dt/dt (21).jpg',
            '../static/img/product/dt/dt (22).jpg',
            '../static/img/product/dt/dt (23).jpg',
            '../static/img/product/dt/dt (24).jpg',
        ],
    },
    {
        txt: '花艺',
        id: 3,
        imgList:[
            '../static/img/product/hy/hy (1).jpg',
            '../static/img/product/hy/hy (2).jpg',
            '../static/img/product/hy/hy (3).jpg',
            '../static/img/product/hy/hy (4).jpg',
            '../static/img/product/hy/hy (5).jpg',
            '../static/img/product/hy/hy (6).jpg',
            '../static/img/product/hy/hy (7).jpg',
            '../static/img/product/hy/hy (8).jpg',
            '../static/img/product/hy/hy (9).jpg',
            '../static/img/product/hy/hy (10).jpg',
            '../static/img/product/hy/hy (11).jpg',
            '../static/img/product/hy/hy (12).jpg',
            '../static/img/product/hy/hy (13).jpg',
            '../static/img/product/hy/hy (14).jpg',
            '../static/img/product/hy/hy (15).jpg',
            '../static/img/product/hy/hy (16).jpg',
            '../static/img/product/hy/hy (17).jpg',
            '../static/img/product/hy/hy (18).jpg',
            '../static/img/product/hy/hy (19).jpg',
            '../static/img/product/hy/hy (20).jpg',
        ],
    },
    {
        txt: '画品',
        id: 4,
        imgList:[
            '../static/img/product/hp/hp (1).jpg',
            '../static/img/product/hp/hp (2).jpg',
            '../static/img/product/hp/hp (3).jpg',
            '../static/img/product/hp/hp (4).jpg',
            '../static/img/product/hp/hp (5).jpg',
            '../static/img/product/hp/hp (6).jpg',
            '../static/img/product/hp/hp (7).jpg',
            '../static/img/product/hp/hp (8).jpg',
            '../static/img/product/hp/hp (9).jpg',
            '../static/img/product/hp/hp (10).jpg',
            '../static/img/product/hp/hp (11).jpg',
            '../static/img/product/hp/hp (12).jpg',
            '../static/img/product/hp/hp (13).jpg',
            '../static/img/product/hp/hp (14).jpg',
            '../static/img/product/hp/hp (15).jpg',
            '../static/img/product/hp/hp (16).jpg',
            '../static/img/product/hp/hp (17).jpg',
            '../static/img/product/hp/hp (18).jpg',
            '../static/img/product/hp/hp (19).jpg',
            '../static/img/product/hp/hp (20).jpg',
            '../static/img/product/hp/hp (21).jpg',
            '../static/img/product/hp/hp (22).jpg',
        ],
    },
    {
        txt: '家具',
        id: 5,
        imgList:[
            '../static/img/product/jj/jj (1).jpg',
            '../static/img/product/jj/jj (2).jpg',
            '../static/img/product/jj/jj (3).jpg',
            '../static/img/product/jj/jj (4).jpg',
            '../static/img/product/jj/jj (5).jpg',
            '../static/img/product/jj/jj (6).jpg',
            '../static/img/product/jj/jj (7).jpg',
            '../static/img/product/jj/jj (8).jpg',
            '../static/img/product/jj/jj (8).jpg',
            '../static/img/product/jj/jj (9).jpg',
            '../static/img/product/jj/jj (10).jpg',
            '../static/img/product/jj/jj (11).jpg',
            '../static/img/product/jj/jj (12).jpg',
            '../static/img/product/jj/jj (13).jpg',
            '../static/img/product/jj/jj (14).jpg',
            '../static/img/product/jj/jj (15).jpg',
            '../static/img/product/jj/jj (16).jpg',
            '../static/img/product/jj/jj (17).jpg',
            '../static/img/product/jj/jj (18).jpg',
            '../static/img/product/jj/jj (19).jpg',
            '../static/img/product/jj/jj (20).jpg',
            '../static/img/product/jj/jj (21).jpg',
            '../static/img/product/jj/jj (22).jpg',
            '../static/img/product/jj/jj (23).jpg',
            '../static/img/product/jj/jj (24).jpg',
            '../static/img/product/jj/jj (25).jpg',
            '../static/img/product/jj/jj (26).jpg',
            '../static/img/product/jj/jj (27).jpg',
            '../static/img/product/jj/jj (28).jpg',
            '../static/img/product/jj/jj (29).jpg',
            '../static/img/product/jj/jj (30).jpg',
        ],
    },
    {
        txt: '饰品',
        id: 6,
        imgList:[
            '../static/img/product/sp/sp (1).jpg',
            '../static/img/product/sp/sp (2).jpg',
            '../static/img/product/sp/sp (3).jpg',
            '../static/img/product/sp/sp (4).jpg',
            '../static/img/product/sp/sp (5).jpg',
            '../static/img/product/sp/sp (6).jpg',
            '../static/img/product/sp/sp (7).jpg',
            '../static/img/product/sp/sp (8).jpg',
            '../static/img/product/sp/sp (9).jpg',
            '../static/img/product/sp/sp (10).jpg',
            '../static/img/product/sp/sp (11).jpg',
            '../static/img/product/sp/sp (12).jpg',
            '../static/img/product/sp/sp (13).jpg',
            '../static/img/product/sp/sp (14).jpg',
            '../static/img/product/sp/sp (15).jpg',
            '../static/img/product/sp/sp (16).jpg',
            '../static/img/product/sp/sp (17).jpg',
            '../static/img/product/sp/sp (18).jpg',
            '../static/img/product/sp/sp (19).jpg',
            '../static/img/product/sp/sp (20).jpg',
            '../static/img/product/sp/sp (21).jpg',
            '../static/img/product/sp/sp (22).jpg',
            '../static/img/product/sp/sp (23).jpg',
            '../static/img/product/sp/sp (24).jpg',
            '../static/img/product/sp/sp (25).jpg',
            '../static/img/product/sp/sp (26).jpg',
            '../static/img/product/sp/sp (27).jpg',
        ],
    },
]
export default config;